import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashNav from "./(dashboard)/_components/dashboard-navbar";
import DashSidebar from "./(dashboard)/_components/dashboard-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#E6EEF6]">
          <DashNav />
          <div className="flex items-start h-full ">
            <DashSidebar />
            <div className="px-[30px] pt-[30px] w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
